### ISSUE TITLE
Getting these stacks working with volumes rather than local bind mounts

### ISSUE THREAD

**Issue by bmmathe** [robinong79/docker-swarm-monitoring#2]
This is great if you are running one host like in the example but if I have 20 hosts it would be nice not to have to copy the dockerdata folder to every host before deploying the stack.

I've been trying for hours to get this to work using volumes rather than bind mounts and I have not been successful.

The issue is with the single file bindings for the config files.  From the look of things you can't create a volume that is a file reference (it always treats the volume as a directory). 

To make things slightly more complicated I'm trying to come up with a solution using the Azure File Docker  Driver so I can reference these files in a cloud share rather than locally on the host.

Any help would be appreciated.

**Comment by robinong79** [comment]
You don't need to to copy the dockerdata for eacht host. The main parts of this setup that uses dockerdata only need 1 instance. Like prometheus and the alertmanagers.

NodeExporter and CAdvisor are initialized Global and will talk and register to the prometheus container.
We are using this setup in a swarm setup and only use 1 central data directory. This is a volume mapped to our main on-premise storage.

Do you wan't a prometheus container on each host? Or do you also want to run prometheus once and then the NodeExporter and CAdvisor on all the servers in your swarm?

I can't help you with the Azure File Docker Driver a.t.m. since we are not working in a cloud setup.

**Comment by robinong79** [comment]
Closed since no response.
